### ISSUE TITLE
Ignore vertical panning

### ISSUE THREAD

**Issue by braincore** [tsdmrfth/react-native-steve#11]
I'm testing this with a `ScrollView`. It's not possible to scroll vertically when swiping on this component as the `PanGestureHandler` captures it. An improvement would be for this component to only capture horizontal panning, but not vertical.

**Comment by tsdmrfth** [comment]
Hi. Thanks for reporting. Today I'll fix this and publish.

**Comment by tsdmrfth** [comment]
Fixed in https://github.com/tsdmrfth/react-native-steve/pull/15

**Comment by tsdmrfth** [comment]
@braincore New version released now. Let me know if that works now

**Comment by braincore** [comment]
Working great!
