### ISSUE TITLE
Decrease reanimated requirement to 2.x

### ISSUE THREAD

**Issue by braincore** [tsdmrfth/react-native-steve#12]
I've been using a fork where I modified the reanimated dependency specification to ^2 to satisfy another dependency that currently only works for reanimated 2.0. Seems to work without a hitch so I suggest making the peer dependency more liberal.

**Comment by tsdmrfth** [comment]
Yes. Peer dependency can be ^2. Currently I am working on RTL support which is a real headache. So a PR from anyone for this would be great

**Comment by braincore** [comment]
Sorry, no experience with RTL :)

**Comment by tsdmrfth** [comment]
I meant a PR for decreasing reanimated version :)

**Comment by braincore** [comment]
Fixed in #16

**Comment by tsdmrfth** [comment]
@braincore New version released now. Let me know if that works now

**Comment by braincore** [comment]
Looks good!
