### ISSUE TITLE
RTL code breaks layouts with fewer than two items

### ISSUE THREAD

**Issue by braincore** [tsdmrfth/react-native-steve#19]
That's at least my guess. Here's the likely offending line:

```
                    const firstKey = keyExtractor(data[firstIndex], firstIndex)
                    const secondKey = keyExtractor(data[secondIndex], secondIndex)
```

The assumption is that the `1` index (whether firstIndex or secondIndex depending on RTL) is valid, which isn't necessarily the case.

**Comment by tsdmrfth** [comment]
Hi. Thanks for reporting. Good catch. I did not like that code but that was the only way to calculate spacing between two items in a correct way. In real world scenario no one would use this component with a single child but still that should be handled.

**Comment by braincore** [comment]
True that a single item isn't the usual use case. But, I'm testing this out for dynamically generated categories and it's very much possible for a category to have only one item.

**Comment by tsdmrfth** [comment]
Right. I'll fix that as soon as possible

**Comment by braincore** [comment]
Any ETA on this? Or should I fork it?

**Comment by tsdmrfth** [comment]
Version 0.4.1 just released

**Comment by braincore** [comment]
Working great. Thank you!
