### ISSUE TITLE
Error if containerStyle is unspecified

### ISSUE THREAD

**Issue by braincore** [tsdmrfth/react-native-steve#20]
I'd expect there to be a sensible default that works in the case that it isn't specified.

**Comment by tsdmrfth** [comment]
containerStyle is added as an empty object in defaultProps

**Comment by braincore** [comment]
I do see that in your code. Not sure exactly what the issue was but I can't reproduce it. Closing.

**Comment by tsdmrfth** [comment]
Is that crashing when you didn't pass containerStyle?

**Comment by braincore** [comment]
That's what was happening. Specifically, the error was in `getContainerHorizontalSpacing` that does the style unpacking. But, now it seems to work after removing `containerStyle`. Perhaps it had to do with updating the library without refreshing the internal state of the app screen.

**Comment by tsdmrfth** [comment]
Yeah, I think so. I want to refactor that part.
